name: Deploy Sylas Front to VPS

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build -- --configuration=production

            - name: Clean remote directory via SSH
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  script: rm -rf /var/www/html/sylas/*

            - name: Deploy
              uses: appleboy/scp-action@v1
              with:
                  host: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  port: 22
                  source: 'dist/sylas-front/browser/*'
                  target: '/var/www/html/sylas'
                  strip_components: 3