name: Deploy Sylas Front to VPS

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Build
              run: ng build --configuration production

            - name: Deploy
              uses: appleboy/scp-action@v1
              with:
                  host: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  port: 22
                  source: 'dist/sylas-front'
                  target: '/var/www/html/Sylas'
                  strip_components: 1